const $ = <T extends Element=HTMLElement>(selector:string)=>document.querySelector<T>(selector);
$('.theme-toggle')?.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('blog-theme',theme)}catch{}});
$('.mobile-menu')?.addEventListener('click',()=>{const drawer=$<HTMLElement>('.mobile-drawer')!;drawer.hidden=!drawer.hidden;$('.mobile-menu')?.setAttribute('aria-expanded',String(!drawer.hidden))});
$('.back-top')?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
const days=$('#site-days');if(days)days.textContent=String(Math.max(0,Math.floor((Date.now()-new Date((days as HTMLElement).dataset.start!).getTime())/86400000)));
document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.closest('.code-block')!.querySelector('code')!.textContent||'');b.textContent='已复制'}catch{b.textContent='请选中代码复制'}}));
$('.share-button')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('.share-button')!.textContent='链接已复制'}catch{$('.share-button')!.textContent='请复制地址栏链接'}});
document.querySelectorAll<HTMLImageElement>('.prose img').forEach(img=>img.addEventListener('click',()=>{const dialog=document.createElement('dialog');dialog.className='lightbox';const full=document.createElement('img');full.src=img.src;full.alt=img.alt;const close=document.createElement('button');close.textContent='关闭';close.onclick=()=>dialog.close();dialog.append(full,close);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal()}));
const dialog=$<HTMLDialogElement>('.search-dialog')!;let searchIndex:any[]|null=null,searchLoading:Promise<void>|null=null,searchError=false;
function renderSearch(){const q=$<HTMLInputElement>('#site-search')!.value.trim().toLowerCase();const box=$('.search-results')!;box.replaceChildren();if(searchIndex===null){box.textContent=searchError?'搜索索引暂时无法加载，请关闭后重试。':'正在加载搜索索引…';return}const found=q?searchIndex.filter(p=>(p.title+' '+p.text).toLowerCase().includes(q)).slice(0,30):[];if(!found.length){const p=document.createElement('p');p.textContent=q?'没有找到相关文章。':'输入关键词，搜索全部公开文章。';box.append(p)}for(const p of found){const a=document.createElement('a');a.className='search-result';a.href=p.path;const strong=document.createElement('strong');strong.textContent=p.title;const excerpt=document.createElement('p');excerpt.textContent=p.excerpt;a.append(strong,excerpt);box.append(a)}}
function loadSearch(){if(searchIndex!==null)return Promise.resolve();if(searchLoading)return searchLoading;searchError=false;searchLoading=(async()=>{try{const response=await fetch('/search-index.json');if(!response.ok)throw new Error('索引加载失败');searchIndex=await response.json()}catch{searchError=true}finally{searchLoading=null;renderSearch()}})();return searchLoading}
$('.search-trigger')?.addEventListener('click',()=>{dialog.showModal();$('#site-search')?.focus();loadSearch();renderSearch()});
$('.search-close')?.addEventListener('click',()=>dialog.close());
dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
$('#site-search')?.addEventListener('input',renderSearch);
const id=$<HTMLElement>('main')?.dataset.documentId;
async function comments(){if(!id||!$('.comment-list'))return;try{const rows=await(await fetch(`/api/public/documents/${id}/comments`)).json();const list=$('.comment-list')!;list.replaceChildren();if(!rows.length)list.textContent='还没有评论，欢迎留下你的想法。';for(const c of rows){const item=document.createElement('div');item.className='comment-item';const name=document.createElement('strong');name.textContent=c.author;const time=document.createElement('time');time.textContent=new Date(c.created_at).toLocaleDateString('zh-CN');const body=document.createElement('p');body.textContent=c.content;item.append(name,time,body);list.append(item)}}catch{$('.comment-list')!.textContent='评论暂时无法加载。'}}
if(id){comments();fetch(`/api/public/documents/${id}/visit`,{method:'POST'}).then(r=>r.json()).then(s=>{if($('.visit-count'))$('.visit-count')!.textContent=s.visits}).catch(()=>{});$('.like-button')?.addEventListener('click',async()=>{try{const r=await fetch(`/api/public/documents/${id}/like`,{method:'POST'});const s=await r.json();if(r.ok){$('.like-count')!.textContent=s.likes;($('.like-button') as HTMLButtonElement).disabled=true}}catch{}})}
$('.comment-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.target as HTMLFormElement;const button=form.querySelector('button')!;button.disabled=true;try{const values=Object.fromEntries(new FormData(form));const r=await fetch(`/api/public/documents/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const result=await r.json();if(!r.ok)throw new Error(result.message||'提交失败');$('.form-status')!.textContent='评论已提交，审核后显示。';form.reset()}catch(e){$('.form-status')!.textContent=(e as Error).message}finally{button.disabled=false}});
const headings=document.querySelectorAll('.prose h1,.prose h2,.prose h3,.prose h4,.prose h5,.prose h6');if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){document.querySelectorAll('.toc a').forEach(a=>a.classList.toggle('current',a.getAttribute('href')===`#${entry.target.id}`))}},{rootMargin:'-70px 0px -70% 0px'});headings.forEach(h=>observer.observe(h))}
