import Fastify from 'fastify';import cookie from '@fastify/cookie';import multipart from '@fastify/multipart';import rateLimit from '@fastify/rate-limit';import staticFiles from '@fastify/static';import {z} from 'zod';
import path from 'node:path';import fs from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {fileURLToPath} from 'node:url';import JSZip from 'jszip';
import {db,dataDir,documents,document,saveDocument,trash,settings,setSettings,defaultSettings,validContentPath} from './db.mjs';
import {passwordHash,verifyPassword,createSession,session,tokenHash} from './auth.mjs';import {renderMarkdown,safeHtml} from './markdown.mjs';
import {enqueueBuild,activeContent} from './publish.mjs';import {markdownUpload,storeMedia} from './uploads.mjs';import {createBackup} from './backup.mjs';
const date=z.string().refine(s=>!Number.isNaN(Date.parse(s)),'日期无效');
const url=z.string().max(2000).regex(/^[^<>\"'\\\u0000-\u001f]*$/,'地址含无效字符').refine(s=>!s||s.startsWith('/')&&!s.startsWith('//')||/^https?:\/\//.test(s),'请使用站内路径或 HTTP 地址');
const docSchema=z.object({kind:z.enum(['post','page']),title:z.string().trim().min(1).max(500),path:z.string().refine(validContentPath,'固定链接无效'),format:z.enum(['markdown','html']),markdown:z.string().max(2000000),date,modifiedAt:date.optional(),categories:z.array(z.string().max(100)).max(20).default([]),tags:z.array(z.string().max(100)).max(50).default([]),excerpt:z.string().max(2000).default(''),cover:url.default(''),pinned:z.boolean().default(false),allowComment:z.boolean().default(true),visibility:z.enum(['public','private']).default('public'),author:z.string().max(100).default('undefim')});
const fail=(status,message)=>Object.assign(new Error(message),{statusCode:status});
function cleanSettings(input){const keys=Object.keys(defaultSettings);const result={};for(const key of keys)if(key in input)result[key]=input[key];const scalar=['title','description','author','bio','location','announcement','email','github','qq','startDate','umamiWebsiteId'];for(const k of scalar)if(k in result&&(typeof result[k]!=='string'||result[k].length>3000))throw fail(400,'设置文本过长或格式无效');for(const k of ['avatar','logo','background'])if(k in result)result[k]=url.parse(result[k]);if('accent' in result&&!/^#[0-9a-f]{6}$/i.test(result.accent))throw fail(400,'主题色格式无效');if('cardOpacity'in result)result.cardOpacity=z.number().min(.5).max(1).parse(result.cardOpacity);if('importAutoPublish' in result)result.importAutoPublish=z.boolean().parse(result.importAutoPublish);for(const kind of ['categories','tags'])if(kind in result){result[kind]=z.array(z.object({id:z.string().optional(),name:z.string().min(1).max(100),slug:z.string().min(1).max(150).regex(/^[\p{L}\p{N}._-]+$/u),description:z.string().max(2000).optional(),color:z.string().optional(),children:z.array(z.string()).optional(),hidden:z.boolean().optional()})).max(1000).parse(result[kind]);if(new Set(result[kind].map(t=>t.slug)).size!==result[kind].length)throw fail(400,'分类或标签路径重复')};if('navigation'in result)result.navigation=z.array(z.object({label:z.string().max(40),href:url})).max(20).parse(result.navigation);if('links'in result)result.links=z.array(z.object({name:z.string().max(100),url,logo:url.optional()})).max(300).parse(result.links);return result}
export async function createApp(){
 const app=Fastify({logger:process.env.NODE_ENV==='production',bodyLimit:3*1024*1024,trustProxy:process.env.TRUST_PROXY==='true'});
 await app.register(cookie);await app.register(multipart,{limits:{fileSize:40*1024*1024,files:20,fields:20}});await app.register(rateLimit,{global:false});await app.register(staticFiles,{root:process.cwd(),serve:false,cacheControl:false});
 app.addHook('onRequest',async(req,reply)=>{reply.header('X-Content-Type-Options','nosniff').header('Referrer-Policy','strict-origin-when-cross-origin').header('X-Frame-Options','SAMEORIGIN');if(req.url.startsWith('/api/')||req.url.startsWith('/admin'))reply.header('Cache-Control','no-store');if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin){const expected=process.env.ADMIN_ORIGIN||`${req.protocol}://${req.headers.host}`;if(req.headers.origin!==expected)throw fail(403,'请求来源无效')}});
 app.setErrorHandler((error,req,reply)=>{if(error instanceof z.ZodError)return reply.code(400).send({message:error.issues.map(x=>x.message).join('；')});const status=error.statusCode||400;return reply.code(status).send({message:status>=500?'服务暂时不可用':error.code==='ERR_SQLITE_ERROR'?'数据冲突，请检查固定链接或重试':error.message})});
 const auth=async(req)=>{req.user=session(req.cookies.blog_session);if(!req.user)throw fail(401,'请先登录');if(!['GET','HEAD'].includes(req.method)&&req.headers['x-csrf-token']!==req.user.csrf)throw fail(403,'会话校验失败，请刷新页面')};
 const exists=id=>{const d=document(id);if(!d)throw fail(404,'内容不存在');return d};
 const publicDoc=async id=>{const d=(await activeContent()).documents.find(d=>d.id===id);if(!d)throw fail(404,'文章不存在');return d};
 app.get('/api/health',async()=>({ok:true}));
 app.post('/api/auth/login',{config:{rateLimit:{max:8,timeWindow:'15 minutes'}}},async(req,reply)=>{const {username,password}=z.object({username:z.string().max(100),password:z.string().max(256)}).parse(req.body);const user=db.prepare('SELECT * FROM users WHERE name=?').get(username);if(!user||!verifyPassword(password,user.password_hash))throw fail(401,'用户名或密码不正确');const s=createSession(username);reply.setCookie('blog_session',s.token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE!=='false',path:'/api',maxAge:7*86400});return {username,csrf:s.csrf}});
 app.get('/api/auth/session',{preHandler:auth},async req=>req.user);
 app.post('/api/auth/logout',{preHandler:auth},async(req,reply)=>{db.prepare('DELETE FROM sessions WHERE token_hash=?').run(tokenHash(req.cookies.blog_session));reply.clearCookie('blog_session',{path:'/api'});return {ok:true}});
 app.post('/api/auth/password',{preHandler:auth},async req=>{const {current,password}=z.object({current:z.string().max(256),password:z.string().min(14).max(256)}).parse(req.body);const user=db.prepare('SELECT * FROM users WHERE name=?').get(req.user.username);if(!verifyPassword(current,user.password_hash))throw fail(400,'当前密码不正确');db.prepare('UPDATE users SET password_hash=? WHERE name=?').run(passwordHash(password),req.user.username);db.prepare('DELETE FROM sessions WHERE username=? AND token_hash<>?').run(req.user.username,tokenHash(req.cookies.blog_session));return {ok:true}});
 app.get('/api/documents',{preHandler:auth},async req=>documents({deleted:req.query.deleted==='true'}));
 app.get('/api/documents/:id',{preHandler:auth},async req=>exists(req.params.id));
 app.post('/api/documents',{preHandler:auth},async req=>saveDocument({...docSchema.parse(req.body),modifiedAt:new Date().toISOString()}));
 app.put('/api/documents/:id',{preHandler:auth},async req=>{const old=exists(req.params.id);if(req.body.updatedAt&&req.body.updatedAt!==old.updatedAt)throw fail(409,'此内容已被另一个窗口更新，请刷新后再编辑');return saveDocument({...old,...docSchema.parse(req.body),id:old.id,modifiedAt:new Date().toISOString()})});
 app.post('/api/documents/:id/publish',{preHandler:auth},async req=>{const d=exists(req.params.id);if(d.visibility==='private'||d.deletedAt)throw fail(400,'请先将文章设置为公开并移出回收站');return {job:enqueueBuild([{id:d.id,data:d}])}});
 app.post('/api/documents/:id/unpublish',{preHandler:auth},async req=>{exists(req.params.id);return {job:enqueueBuild([{id:req.params.id,data:null}])}});
 app.post('/api/documents/:id/trash',{preHandler:auth},async req=>{const d=exists(req.params.id);trash(d.id);return {job:enqueueBuild([{id:d.id,data:null}])}});
 app.post('/api/documents/:id/restore',{preHandler:auth},async req=>{exists(req.params.id);trash(req.params.id,true);return document(req.params.id)});
 app.get('/api/documents/:id/revisions',{preHandler:auth},async req=>{exists(req.params.id);return db.prepare('SELECT id,created_at,reason FROM revisions WHERE document_id=? ORDER BY created_at DESC').all(req.params.id)});
 app.get('/api/documents/:id/revisions/:revision',{preHandler:auth},async req=>{const r=db.prepare('SELECT * FROM revisions WHERE id=? AND document_id=?').get(req.params.revision,req.params.id);if(!r)throw fail(404,'版本不存在');return {...r,data:JSON.parse(r.data)}});
 app.post('/api/documents/:id/revisions/:revision/restore',{preHandler:auth},async req=>{const old=exists(req.params.id);const r=db.prepare('SELECT data FROM revisions WHERE id=? AND document_id=?').get(req.params.revision,req.params.id);if(!r)throw fail(404,'版本不存在');const d=JSON.parse(r.data);return saveDocument({...old,...d,path:old.path,id:old.id,modifiedAt:new Date().toISOString()},'restore-revision')});
 app.post('/api/preview',{preHandler:auth},async req=>{const {source,format}=z.object({source:z.string().max(2000000),format:z.enum(['markdown','html'])}).parse(req.body);return {html:format==='html'?safeHtml(source):await renderMarkdown(source)}});
 app.post('/api/import',{preHandler:auth},async req=>{const parsed=[],seen=new Set();for await(const part of req.files()){const payload=await markdownUpload(await part.toBuffer(),part.filename);for(const raw of payload.documents){const d=docSchema.parse({...raw,visibility:'public'});if(seen.has(d.path)||db.prepare('SELECT id FROM documents WHERE path=?').get(d.path))throw fail(409,`导入路径重复：${d.path}，请修改 Front Matter 中的 slug 或 permalink`);seen.add(d.path);parsed.push(d)}}if(!parsed.length)throw fail(400,'没有上传文件');const result=parsed.map(d=>saveDocument(d));const auto=settings().importAutoPublish;return {documents:result,job:auto?enqueueBuild(result.map(d=>({id:d.id,data:d}))):null}});
 app.get('/api/media',{preHandler:auth},async()=>db.prepare('SELECT * FROM media ORDER BY created_at DESC').all());
 app.post('/api/media',{preHandler:auth},async req=>{const result=[];for await(const f of req.files())result.push(await storeMedia(await f.toBuffer(),f.filename));return result});
 app.get('/api/comments',{preHandler:auth},async()=>db.prepare('SELECT c.*,d.path, json_extract(d.data,\'$.title\') AS document_title FROM comments c JOIN documents d ON d.id=c.document_id ORDER BY c.created_at DESC').all());
 app.patch('/api/comments/:id',{preHandler:auth},async req=>{const change=z.object({status:z.enum(['approved','pending','hidden']),content:z.string().max(5000).optional()}).parse(req.body);const c=db.prepare('SELECT * FROM comments WHERE id=?').get(req.params.id);if(!c)throw fail(404,'评论不存在');db.prepare('UPDATE comments SET status=?,content=? WHERE id=?').run(change.status,change.content??c.content,c.id);return {ok:true}});
 app.get('/api/settings',{preHandler:auth},async()=>settings());
 app.put('/api/settings',{preHandler:auth},async req=>{const before=settings(),next=cleanSettings(req.body);db.exec('BEGIN IMMEDIATE');try{for(const type of ['categories','tags'])if(next[type]){const renames=new Map(before[type].filter(old=>next[type].some(t=>t.id&&t.id===old.id&&t.name!==old.name)).map(old=>[old.name,next[type].find(t=>t.id===old.id).name]));for(const row of db.prepare('SELECT id,data,published_data FROM documents').all()){const draft=JSON.parse(row.data),live=row.published_data?JSON.parse(row.published_data):null;for(const data of [draft,live].filter(Boolean))data[type]=(data[type]||[]).map(name=>renames.get(name)||name);db.prepare('UPDATE documents SET data=?,published_data=? WHERE id=?').run(JSON.stringify(draft),live?JSON.stringify(live):null,row.id)}}setSettings(next);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return settings()});
 app.post('/api/build',{preHandler:auth},async()=>({job:enqueueBuild()}));
 app.get('/api/jobs',{preHandler:auth},async()=>db.prepare('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 50').all());
 app.get('/api/jobs/:id',{preHandler:auth},async req=>{const row=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!row)throw fail(404,'任务不存在');return row});
 app.get('/api/export',{preHandler:auth},async(req,reply)=>{const zip=new JSZip();for(const d of [...documents(),...documents({deleted:true})]){const meta={title:d.title,permalink:d.path,date:d.date,categories:d.categories,tags:d.tags,visibility:d.visibility,deleted:!!d.deletedAt};const filename=`${d.deletedAt?'trash':d.visibility==='private'?'private':'documents'}/${d.id}.${d.format==='html'?'html':'md'}`;zip.file(filename,`---\n${Object.entries(meta).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n')}\n---\n\n${d.markdown}`)}zip.file('settings.json',JSON.stringify(settings(),null,2));reply.header('Content-Disposition','attachment; filename="blog-content.zip"').type('application/zip');return zip.generateAsync({type:'nodebuffer'})});
 app.post('/api/backup',{preHandler:auth},async()=>{const file=await createBackup();return {name:path.basename(file)}});
 app.get('/api/backups/:name',{preHandler:auth},async(req,reply)=>{const name=req.params.name;if(!/^[\w.-]+\.zip$/.test(name))throw fail(400,'文件名无效');reply.header('Content-Disposition',`attachment; filename="${name}"`);return reply.sendFile(name,path.join(dataDir,'backups'))});
 app.get('/api/public/documents/:id/comments',async req=>{await publicDoc(req.params.id);return db.prepare("SELECT id,author,content,created_at,parent_id FROM comments WHERE document_id=? AND status='approved' ORDER BY created_at").all(req.params.id)});
 app.post('/api/public/documents/:id/comments',{config:{rateLimit:{max:3,timeWindow:'10 minutes'}}},async req=>{const d=await publicDoc(req.params.id);if(!d.allowComment)throw fail(403,'此文章已关闭评论');const c=z.object({author:z.string().trim().min(1).max(60),email:z.union([z.literal(''),z.email()]).optional(),content:z.string().trim().min(1).max(5000),website:z.string().max(200).optional()}).parse(req.body);if(c.website)return {ok:true};db.prepare('INSERT INTO comments VALUES (?,?,?,?,?,?,?,?)').run(randomUUID(),d.id,null,c.author,c.email||null,c.content,'pending',new Date().toISOString());return {ok:true}});
 app.post('/api/public/documents/:id/visit',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const d=await publicDoc(req.params.id);const key=`visit_${tokenHash(d.id).slice(0,12)}`;if(!req.cookies[key]){db.prepare('UPDATE stats SET visits=visits+1 WHERE document_id=?').run(d.id);reply.setCookie(key,'1',{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE!=='false',path:'/api/public',maxAge:3600})}return db.prepare('SELECT visits,likes FROM stats WHERE document_id=?').get(d.id)});
 app.post('/api/public/documents/:id/like',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req,reply)=>{const d=await publicDoc(req.params.id);const key=`like_${tokenHash(d.id).slice(0,12)}`;if(!req.cookies[key]){db.prepare('UPDATE stats SET likes=likes+1 WHERE document_id=?').run(d.id);reply.setCookie(key,'1',{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE!=='false',path:'/api/public',maxAge:365*86400})}return db.prepare('SELECT visits,likes FROM stats WHERE document_id=?').get(d.id)});
 app.get('/*',async(req,reply)=>{
  const route='/'+(req.params['*']||'');if(route.split('/').some(s=>s.startsWith('.')||s.includes('\\')||s.includes('\0')))throw fail(404,'页面不存在');
  const safeFile=(root,relative)=>{const file=path.resolve(root,relative);if(!file.startsWith(path.resolve(root)+path.sep))throw fail(404,'页面不存在');return file};
  const readable=async f=>{try{return(await fs.stat(f)).isFile()}catch{return false}};
  if(route.startsWith('/api/'))throw fail(404,'接口不存在');
  if(route==='/admin')return reply.redirect('/admin/');
  if(route.startsWith('/admin/')){const root=path.resolve('dist/admin');const relative=route.slice(7)||'index.html';let file=safeFile(root,relative);if(!await readable(file))file=path.join(root,'index.html');return reply.sendFile(path.relative(root,file),root)}
  if(route.startsWith('/upload/')){const root=path.join(dataDir,'media');const file=safeFile(root,route.slice(1));if(await readable(file)){reply.header('Cache-Control','public, max-age=31536000, immutable');return reply.sendFile(path.relative(root,file),root)}}
  let root=path.join(dataDir,'current/site');try{await fs.access(root)}catch{root=path.resolve('dist/site')}
  const relative=route.slice(1)||'index.html';let file=safeFile(root,relative);if(!await readable(file))file=safeFile(root,path.join(relative,'index.html'));
  if(!await readable(file)){reply.code(404);return reply.sendFile('404.html',root)}
  reply.header('Cache-Control',route.startsWith('/_astro/')?'public, max-age=31536000, immutable':route.startsWith('/assets/')?'public, max-age=86400':'public, max-age=0, s-maxage=300, stale-while-revalidate=60');return reply.sendFile(path.relative(root,file),root);
 });
 return app;
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===path.resolve(process.argv[1])){const app=await createApp();await app.listen({host:process.env.HOST||'127.0.0.1',port:Number(process.env.PORT||4322)})}
